### ISSUE TITLE
Migration Stories area has scrollwheels

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#271]
![image](https://user-images.githubusercontent.com/972891/74891179-22307b80-533b-11ea-9775-ba9836406f7a.png)

**Comment by KingDarBoja** [comment]
@orta this is caused by the following scss:

```scss
#index .migrations {
  overflow-x: hidden;
}
```

Should be `overflow`.
