### ISSUE TITLE
Docs nav should have cursor: pointer

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#502]
Probably want

```css
nav#sidebar > ul > li button {
  cursor: button;
}
```

but it's late here for me to start futzing and breaking the build more.

![cursor](https://user-images.githubusercontent.com/972891/79103373-4730e180-7d21-11ea-9bdb-c8bd07019475.gif)
