### ISSUE TITLE
Imported types from external libraries resolve to `any`

### ISSUE THREAD

**Issue by millsp** [microsoft/TypeScript-Website#92]
In this [example](https://www.typescriptlang.org/play/index.html?ts=3.7-Beta&ssl=3&ssc=13&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgQTgXzgMyhEcBEMAzgLQwQQA2ARgKaUz4DcAUCzAJ5i1wAacAXhQA6AB4sgA), the type `X` resolved to `any` instead of:
```ts
// an opaque type of x
"x" & {
    __type: "x";
}
```

And [this shouldn't work](https://www.typescriptlang.org/play/index.html?ts=3.7-Beta#code/JYWwDg9gTgLgBAKjgQwM5xgIzgMyhEOAIhlQFoYIIAbTAU2piIG4AoVmATzDrgA04AXgyYAdAGEIAOwDGyGAB4A2gEYANHABMAXQ1KAzBoAs2gHxwA9BbgB3fFIDmrIA) but **does** autocomplete on the import. It is incorrect because `Concat` can only be accessed from `tb.T` or `tb.Tuple`. So it seems like there is a confusion between namespaces and modules with the playground.

I think it is important to note that types which are exposed from top-level (not modules in modules) do work. But not when you have types -> in modules -> in modules. Something that is of the form:
```yaml
ModuleA:					# A Module   that exports
 - SubModuleA1				# Submodules that export
   - Types					# Multiple types
 - SubModuleA2
   - Types
ModuleB:
 - SubModuleB1
   - Types
 - SubModuleB2
   - Types
export All:					# All parents exported
 - ModuleA
 - ModuleB
```
